export default function Header() {
  return (
    <>
      <title>Next.js 13.4 + Tailwind CSS + TypeScript</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      <link rel='icon' href='/amazon-2.svg' />
    </>
  );
}
