import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clone da Amazon.com.br",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <Header />
      <body className={inter.className}>
        {/* <h1>Isto deve aparecer em todas as páginas</h1> */}
        {children}
      </body>
    </html>
  );
}
